### PR TITLE
Week mode: Pick a whole week instead of a day

### PR DESCRIPTION
**Pull request by leizhao4**
I added a new option `pickWholeWeek`. When set to `true`, instead of picking a day, you can pick a whole week. Hope it helps.

Note: I didn't change a lot to the original implementation. Technically you are still picking one day, but the entire row is highlighted. You will need to calculate your week's start and end. See the example for details.

### CODE REVIEW

**Comment by leizhao4** [comment]
I just renamed `weekMode` as `pickWholeWeek` which is easier to understand.

**Comment by maprules1000** [comment]
Bump. Any chance on seeing this merged soon @dbushell ? Would prefer not to work off a fork.

**Comment by aspic** [comment]
:+1: on the bump

**Comment by hugoruscitti** [comment]
I think this is a nice feature, any update on this merge?

**Comment by leizhao4** [comment]
Rebased.

**Comment by hugoruscitti** [comment]
any update? i would be great if it was 📦  :P

**Pull request merged**
