### PR TITLE
add config option to show days in next and previous months

### PR DESCRIPTION
**Pull request by eadmundo**
I needed this for a project we're working on, hopefully others might find it useful as well!

It provides a config option to render days that are outside the current month, but greyed out.

### CODE REVIEW

**Comment by jamsinclair** [comment]
Any update on whether this is a foreseeable config option to be added to Pikaday? 

Nevertheless, awesome and simple branch, very useful. Thanks @eadmundo :+1:

**Comment by amigolargo** [comment]
+1 Thanks @eadmundo

**Comment by MaxenceDupressoir** [comment]
+1 Thanks @eadmundo

**Comment by MaxenceDupressoir** [comment]
+1 Thanks @eadmundo

**Comment by eadmundo** [comment]
Move to this PR: https://github.com/dbushell/Pikaday/pull/381

**Pull request closed without merging**
