### PR TITLE
Remove unecessary exports from bower

### PR DESCRIPTION
**Pull request by joscha**
This removes artifacts published to bower that are not needed.

### CODE REVIEW

**Comment by rikkert** [comment]
Is the changelog not something you want from bower?

**Comment by joscha** [comment]
Generally I'd say no, because I don't need it in production, but I am more than happy to remove it from the diff if that is what is keeping this PR open ;)

**Comment by rikkert** [comment]
Yes, if you can take it out I would be glad to merge.

**Comment by joscha** [comment]
@rikkert done!

**Comment by joscha** [comment]
Nice! Thank you!

**Pull request merged**
