### PR TITLE
Register click and touch event separately

### PR DESCRIPTION
**Pull request by szwacz**
Fix for https://github.com/dbushell/Pikaday/issues/374
Credit goes to @kaib84 but I'm doing the PR because of lack of response from that gentleman.

### CODE REVIEW

**Comment by nathancahill** [comment]
Beyond that, it fixes #276, #301, #303, #324, #366 and #386. @rikkert, this should be merged and all of those can be closed.

**Comment by rikkert** [comment]
Ok, this makes sense. But didn't we have this before and it still gave issues?
Also doesn't this result in _onMouseDown running twice because touch devices still handle mousedown?

**Comment by nathancahill** [comment]
As I understand it (and from my limited testing on my devices) even when both listeners, only one or the other fires on click/tap. It looks like @kaib84 did more testing in #374

**Comment by szwacz** [comment]
Indeed the event fires twice! But followed advice from this: http://www.html5rocks.com/en/mobile/touchandmouse/ and it isn't any more.

**Comment by nathancahill** [comment]
:+1: thanks @szwacz

**Comment by duizendnegen** [comment]
awesome, thanks

**Pull request merged**
