### PR TITLE
Add option make keyboard support configurable, fixes #607

### LINKED ISSUE #607: Option to disable keyboard support
We have a setup where we require different inputs, for example mouse + external remote.
With the release of 1.5.1 using the external remote arrow keys now triggers the datepicker to change the date.
We need to avoid this. Is there any simple way to disable this behaviour at the moment?
If not would you be interested in a pull request that would add an option to enable and disable this functionality?

### PR DESCRIPTION
**Pull request by IngoAlbers**

### CODE REVIEW

**Comment by johman10** [comment]
@pierred69: I would love to get this merged to. In the meantime I found a custom solution which works for us in another project.

```javascript
picker = new Pikaday();
document.removeEventListener('keydown', picker._onKeyChange);
```
This kind of just removes the eventListener from the DOM and solves the problem.

**Comment by alpha-and-omega** [comment]
Any Idea how to use the "document.removeEventListener" hack in jQuery Pikaday plugin ?

**Comment by johman10** [comment]
@alpha-and-omega in theory the method I described should work. jQuery is just an extension of JS. Just try the code and see if it works. Else, maybe look into: http://api.jquery.com/off. That might be what you need.

**Comment by kaldras** [comment]
Any update on when this will be merged? We need a option like this and would prefer not to make a custom hack for the plugin.

**Comment by ajhsu** [comment]
Since this option has been merged in June 2017; When will 1.7.0 be released on npm, so that we can take the advantage of this option?

**Comment by rikkert** [comment]
Will do asap thanks for the reminder

**Comment by ajhsu** [comment]
@rikkert It's good to know that! Thanks in advance 👍

**Pull request merged**
