### PR TITLE
Allow multiple input formats, add onClear callback for better Ember/Knockout/etc integration and allow other date libraries instead of Moment.js

### LINKED ISSUE #61: Update maxDate() and Clear options?
Hello,

I'm struggling to achieve the following beaviours. 

I want to have maxDate() set as default, but I'd like to override this to null in certain situations.

Is it possible to remove the maxDate option without it being something like maxDate: new Date("200 years from now?").

Also, is it possible the clear the date from the picker? Something like picker.clear()?

### PR DESCRIPTION
**Pull request by bjbrewster**
Thanks for creating this awesome and yet simple date picker. We are using this library on a fundraising portal raising money for charity so know that its helping make a difference in the world. We needed a few changes to make it easier to integrate with Ember.js so I would like to contribute back to your project.

This change is loosely based on #57 to add callback on clear/invalid date and also fixes #61, #48, #15, #93, #98.  I decided upon `onClear` for the name of the callback, in the same vein as `onSelect`, named after the method `clearDate()` that I extracted from `setDate()`. Feel free to suggest better names. It was very tempting to call `onSelect` callback with `null` for empty/invalid date, but this would most likely break a lot of code by the Pikaday community that relies on the callback always having a valid date so a new callback must be introduced instead.  I would also like to add a suite of automated JS tests to improve code quality.
- Cleaned up `setDate()` so both null date and invalid date string clear the current selection.
- Extracted `clearDate()` method from `setDate()` for clearing the current selection with options for clearing the input field (if set) and preventing `onClear` callback.
- `onClear` callback is called by `clearDate()` so users can be notified of invalid/empty date. The user's callback can get the field text value to show a required validation message if empty or invalid date validation message if not empty.
- `onSelect` and `onClear` are useful when integrating with MVC frameworks such as Knockout.js and Ember.js where `onSelect` and `onClear` sets and clears the binding/component's date value. 
- Added examples for Knockout (#48) and Ember.
- `clearInvalidInput` option can be set to `true` to automatically clear the input field value (if `field` is set) on invalid input. This is a simple way of telling the user the entered date is invalid. 
- `parseDate()` method was extracted from `_onInputChange()` to remove duplicate date string parsing in Pikaday constructor for `defaultDate` and in `setDate()` (was only parsing with JS Date.parse?).
- `parseDate()` method was added to Pikaday prototype instead of a helper/private method to allow for overriding both `toString()` and `parseDate()` on Pikaday.prototype to support other JS date libraries. 
  See Datejs and Sugar examples.
- Fixed issue #98 with Datejs where Date.parse() returns null instead of NaN for invalid input which caused a default date of 1/1/1970 in empty input fields.
- A big feature of Moment.js is that it allows for multiple input formats. `inputFormats` option was added to allow users to specify an array of allowed input formats. Defaults to the display format. Moment example updated accordingly.
- Added fix for issue #93 where wrong month is sometimes shown when minDate's year > default selected date. There's a separate issue where setMinDate does not update the internal min/maxMonth and min/maxYear used in `draw` method.
- README updated accordingly (including defaultDate expected type #15)

### CODE REVIEW

**Comment by drewcovi** [comment]
So is this PR dead?

**Comment by mhkeller** [comment]
I still think it's an improvement.

**Comment by mazing** [comment]
Great PR. Why isn't it accepted?

**Comment by jaconi** [comment]
I find this PR very useful. Any chances it will be accepted?

**Comment by gliesche** [comment]
+1

**Comment by foohooboo** [comment]
@bjbrewster @mhkeller Is this PR dead?  Is it safe to replace into my existing code that is already using the current pikaday?  The functionality I'm wanting is the multiple input formats.

**Comment by rikkert** [comment]
Yes, use the parse and toString method that have been added.

**Pull request closed without merging**
