### PR TITLE
Made picker 100% responsive

### PR DESCRIPTION
**Pull request by olitomas**
The picker is 100% responsive with a couple of css lines. Please check it out,  I really hope you consider merging.

Best regards, Oli

### CODE REVIEW

**Comment by olitomas** [comment]
@dbushell

**Comment by tsteuwer** [comment]
Why did this get reverted?

**Comment by rikkert** [comment]
Layout didn't look good otb anymore.

**Comment by olitomas** [comment]
I am using this in production and everything is tip top. What does otb stand for (off the boat ?)

**Pull request merged**
