### PR TITLE
Allow user select dates in previous and next months if they are rende…

### PR DESCRIPTION
**Pull request by braczek**
Adds functionality that allows user to select date that is in prev / next month based on setting passed to options. By default calendar is behaving as it was before, passing `enableSelectionDaysInNextAndPreviousMonths: true` allows selection of those dates.

### CODE REVIEW

**Comment by kevinob11** [comment]
I'd love this, any chance we can get it merged?

**Comment by matthijsbierman** [comment]
Was looking for this functionality. +1 to get this in.

**Comment by kevinob11** [comment]
Thanks for the quick merge and doc updates! When do you expect this will be released to NPM?

**Comment by wstoettinger** [comment]
i just updated to the latest version (1.6.1) which has this feature included but it doesn't seem to work despite setting the option `enableSelectionDaysInNextAndPreviousMonths: true`. Any recommendations?

ps: `showDaysInNextAndPreviousMonths: true` works as expected

**Comment by kevinob11** [comment]
Works great for me after updating to the latest about 4 days ago.

**Comment by rikkert** [comment]
See the example

**Comment by wstoettinger** [comment]
Okay thanks! I solved it!

**Pull request merged**
