### PR TITLE
Show days in next and previous months

### PR DESCRIPTION
**Pull request by eadmundo**
see https://github.com/dbushell/Pikaday/issues/176 for previous discussion

### CODE REVIEW

**Comment by jonathansimmons** [comment]
While this Does successfully show the days in the previous and next month, the `button.pika-button` being added is not being given the right date data attributes.

Which means should you like myself have a desire to also allow the user to select a day in the previous month, the date is not properly set. 

I know that might now have been your original goal but I think for this to be considered whole it should probably be creating valid buttons. 

I'm stacked on a project at the moment but might be able to help in a few weeks if this isn't something you can get around to.

**Comment by eadmundo** [comment]
The markup does have the correct date data attributes - the reason the user can't select a day in the next/previous month is because the pointer events were set to none in the css. I've changed that, and they can now be selected.

**Comment by jonathansimmons** [comment]
I wasn't arguing that you should change the css you added. I think by default most people won't want them to be selectable. It's easy enough to change css yourself.

My tests still show that the button data is not being generated right. Here is a screenshot where you'll see the  31st of july has the `data-pika-month="7"` when it should be `data-pika-month="6"`

And in the last row the first days of Sep still have `data-pika-month="7"` when it should be `data-pika-month="8"`
screen shot 2015-08-14 at 12 02 01 pm

**Comment by eadmundo** [comment]
ahhh I see - sorry. Yup I can fix that.

**Comment by Rhymond** [comment]
fix is ready?

**Comment by isupersid** [comment]
any updates on this? I need this update as well.

**Comment by LordZardeck** [comment]
Is there anything holding this up? We need this for our project.

**Comment by eadmundo** [comment]
> Is there anything holding this up? We need this for our project.

just busy with other things! sorry. Should be good to go now.

**Comment by nathancahill** [comment]
I think that was directed at @dbushell, who seems to have left the project. @rikkert, can you ping me about maintaining this project? I'd love to jump in and work through the backlog. This is the best lightweight datepicker out there and I hate to see it fall apart. My email is in my profile.

**Comment by LordZardeck** [comment]
I agree with @nathancahill, this is a great project. The best I've seen. I'd be willing to help as well.

**Comment by rikkert** [comment]
Thanks for the mention.
I'm definitely still maintaining the project and saying it is falling apart it is a little harsh.
@nathancahill thanks for all your great help and I will mail you to see how we can bring it together.

**Comment by marsbergen** [comment]
Hi guys, I am looking for a JS calendar lib and Pikaday seems the right one I need, and this pull request is one of the design requirements. Is there any status that this PR will be merged soon? Thanks!

**Pull request merged**
