### PR TITLE
Add CSS-classes indicating position

### PR DESCRIPTION
**Pull request by rubenswieringa**
This feature allows for the styling of the datepicker to change according to where it is relative to field – for example datepickers that are styled to have a pointer that points to a date-input.

CSS-classnames (open to suggestions):
* `top-aligned`
* `bottom-aligned`
* `left-aligned`
* `right-aligned`

I had some trouble getting your tests and linting to work. If you want me to do something for that then could you give me some pointers on how to get that up and running?

### CODE REVIEW

**Comment by rikkert** [comment]
If you can also add to the readme and add an example I'm happy to merge.
Running: npm run lint should warn you about linting errors.

**Comment by rubenswieringa** [comment]
The CSS-classes are now mentioned in the readme and here's an example: https://plnkr.co/edit/IS6gpzw0dg1hUZzXYHk8?p=preview

…I take it you meant a working example, rather than a code-example in the documentation?

Thanks :)

**Comment by rikkert** [comment]
That is great thanks, I meant in the example folder of this repo.

**Comment by rubenswieringa** [comment]
> I meant in the example folder of this repo.

Lol, I'll get on it tomorrow and will hit you up.

**Comment by rubenswieringa** [comment]
@rikkert Should be good now, let me know if there's anything I can improve!

**Pull request merged**
