### PR TITLE
Added ARIA and keyboard support for better accessibility

### PR DESCRIPTION
**Pull request by mrenty**
With these additions to your code it is more accessible for people with a disability.

### CODE REVIEW

**Comment by elgubenis** [comment]
was just looking for something like this, we hope that gets merged

**Comment by sathomas** [comment]
Adding accessibility is a big win. If there is anything I can do to help move this pull request along (testing, code review, ...), let me know.

**Comment by mrenty** [comment]
Hi Stephen, you may do a code review if you like. Are you a contributor of Pikaday?

**Comment by Robdel12** [comment]
Hey @mrenty great work! Thanks for getting the accessibility conversation started on Pikaday. I'd like to help finishing this off and getting this merged for [global accessibility awareness day](http://www.globalaccessibilityawarenessday.org/).

I've created a small video of what it's like to use what you've got so far [with VoiceOver](https://youtu.be/eD2L2F3kg6Q). It's a great improvement, but we still need to let the screen reader know what they're selecting. 

I can help in any way you'd like. Let me know how I can help :)

**Comment by mrenty** [comment]
Hi @Robdel12, nice to hear that you like it 😉
I'll take a look at it this week to see where I can improve the accessible experience, but if you have suggestions or want to make a PR feel free to do so.
I'll keep you posted!

**Comment by rikkert** [comment]
Fixed by #522

**Pull request closed without merging**
