### PR TITLE
Goto today button

### PR DESCRIPTION
**Pull request by mmolhoek**
hi David,

I thought this might be handy.

Greetings,

Mischa

### CODE REVIEW

**Comment by chrisa-fastpay** [comment]
I definitely second this, it's a much needed feature.

**Comment by mmolhoek** [comment]
ok, it can be merged now :)

**Comment by rajivseelam** [comment]
Hi,

Any tentative date on when this might be merged?

**Comment by samuelg0rd0n** [comment]
Hi, will this be merged in the near future please? :-)

**Review by pecochan — COMMENTED** [review]
works perfectly for me.

**Comment by martinbarilik** [comment]
Why is this not yet integrated in library ? Seriously, it's ridiculous ...

**Pull request closed without merging**
