### PR TITLE
Add an optional formatter function option

### PR DESCRIPTION
**Pull request by everdimension**
This is a pull request for https://github.com/dbushell/Pikaday/issues/653

I decided to give a "formatter" function a higher proriority than formatting with moment: if someone uses this option he might still wish to do custom formatting even if moment is available (and may be even with its help).

Again, this is the logic (it pretty much preserves the current flow):

* if current date is not a valid object, return `''`
* if custom formatter is provided, use it and pass current date object to it and a current `format` string
* if not, use `moment` to format date according to `format` string
* else use .toDateString()

If the `formatter` option is not provided the library behaves the same as before.

### CODE REVIEW

**Comment by everdimension** [comment]
@rikkert please take a look
Is this library being maintained?

**Comment by rikkert** [comment]
Yes it is. 
Why would you use moment but not for formatting?

**Comment by everdimension** [comment]
I don't understand the question.

The idea of a "formatter" function is that it enables you to add custom formatting however you like, be that another date library or no library whatsoever or some crazy formatting with moment for which `moment.format` is not enough, you still get formatted dates and not the result of `.toDateString()`.

**Comment by alpha-and-omega** [comment]
I had intention to write similar code since current moment integration looks like a dirty hack, as if a Pikaday were a part of a moment. And because moment is 50kb!
No need for a new function 'formatter' option. Just use these standard names from Pikaday and Date functions:
1) toString - obviously
2) parse - as in Date
3) format - abviously again
Done!
I will create alternative Pull request with much less code and parse implementation.

**Comment by alpha-and-omega** [comment]
Done, check it out: #670

**Comment by everdimension** [comment]
@alpha-and-omega I like `toString` name better than `formatter` name, thanks.

> I will create alternative Pull request with much less code and parse implementation.

Sorry, your PR doesn't have less code, it has more, it just lacks tests.

Anyway, let's not compete about this; you could submit a PR to my branch so that both our changes would be in this PR.

The problem is that I don't think maintainers here are very active. There are lots of good PRs here waiting for a long time without action.

**Comment by alpha-and-omega** [comment]
@everdimension, you are right, that cade are tests, I missed that.
Well, then you need to correct an error then too, right here: return moment(this._d).format(format); not sure about the rest.

**Comment by alpha-and-omega** [comment]
@everdimension you can get my code, I don't know how to "submit a PR to"

**Comment by everdimension** [comment]
Updated the pull request. Renamed 'formatter' —> 'toString', added 'parse' option, added tests;

@rikkert if this change is ok I can update README in a separate commit or in another PR.

**Comment by alpha-and-omega** [comment]
Good. And one less error in code too! ;)

**Comment by rikkert** [comment]
Yes README would be good, I'm also adding an example

**Comment by alpha-and-omega** [comment]
I met problems with is.
For example setDate will not use a new parse function, and this is because date parsing is spreaded and duplicated everywhere, and this is why Pikaday code stinks :)

To make code more clear, date parsing should be implemented in distinct method. This will decrease code size too.

But, who cares! Don't you rikkert ? Number of forks is more important!

**Comment by rikkert** [comment]
Well, actually it is the balance act of adding more and more features that people keep PR in and a clean small code base.
It is not easy @alpha-and-omega

**Comment by wstoettinger** [comment]
imho this is a very important feature to keep the total footprint small. Formatting is an essential functionality and having to use a rather huge moment.js kills the advantage of using a small datepicker.

any chances of this getting merged soon?

**Comment by everdimension** [comment]
@alpha-and-omega 
>I met problems with is.
For example setDate will not use a new parse function

I've taken a look at the current `setDate` implementation and I don't believe it should be altered. As per documentation it's [supposed](https://github.com/dbushell/Pikaday#get-and-set-date) to take a valid date string and it [doesn't even rely on `moment`](https://github.com/dbushell/Pikaday/blob/9750298c6729cf86064eaf82db0cc99176eb0092/pikaday.js#L751-L790), therefore it shouldn't rely on the introduced `parse` function, either. Even the name `parse` means that it's supposed to take care of the *user input* and it shouldn't be used for programmatic setters like `setDate`. The user of the library can use whatever parsing means he wants to pass a valid date object or a valid date string to `setDate`.

---

@rikkert is this ready to be merged?
Should we take care of updating `readme` in a separate PR?

**Comment by rikkert** [comment]
No, the readme addition can be added in this pr and I will add an example
to this pr and then I will merge.

**Comment by alpha-and-omega** [comment]
@everdimension, yes, I know that, but it is so tempting to replace Data.parse with global parser. Be it Moment if availabe, Date.parse by default or external call optionaly, this will make code smaller and more clear. I met a problem with it and I bet others too.
This patch works as intended and I use it in production already.

**Comment by rikkert** [comment]
@everdimension can you please still commit and push the README addition to this PR?

**Comment by everdimension** [comment]
Right, sorry for the delay.

I'll try to do it later today!

**Comment by everdimension** [comment]
@rikkert updated the README.

**Comment by rikkert** [comment]
Merged

**Pull request closed without merging**
