### PR TITLE
Do not set position out of viewport

### PR DESCRIPTION
**Pull request by laoneo**
On small screens it can be that pikady is positioned out of screen. To be consistent I'v added a test for the top property too.

### CODE REVIEW

**Comment by laoneo** [comment]
Do you have plans to ship this fix in the next release or do I have to patch it manually in my product?

**Comment by arp242** [comment]
I don't think this is maintained unfortunately.

You can do the same a bit shorter with `Math.max()` btw :-)

    this.el.style.left = Math.max(left, 0) + 'px';
    this.el.style.top =  Math.max(top, 0) + 'px';

**Comment by rikkert** [comment]
Isn't this related to the positions stuff we have?
/examples/positions
I thought if it wouldn't fit one way it would automatically position somewhere else?
Have been out of this for a while so can be totally unrelated, please let me know.

**Comment by laoneo** [comment]
The problem is when screens are small then it goes over the screen.

**Comment by JoshWhite** [comment]
Am I right in thinking this has been merged into master, but not yet published?

**Pull request merged**
