### PR TITLE
Add black triangle down after month and year menus

### PR DESCRIPTION
**Pull request by nathancahill**
This looks much more user friendly to me:

### CODE REVIEW

**Comment by timaschew** [comment]
it's a bit confusing that the arrow is only placed after the the year, it looks like if you click on it you can change month and year within one select, but it's only the year. so it would be more clear if the month would also have an arrow.

**Comment by philippeluickx** [comment]
I fixed this with some CSS:

.pika-label:after {
  content:" \25be";
}
.pika-label:hover {
  background-color: #aaa;
}

**Comment by rikkert** [comment]
I like the CSS options beter, what do you guys think?
I could add it is a theming example.

**Comment by nathancahill** [comment]
Yeah, CSS is way better.

**Comment by robd** [comment]
Also worth noting that quite a few browsers do not support this glyph by default: http://unicode.johnholtripley.co.uk/25BE/ so it's worth testing on devices you care about.

**Comment by bgdz** [comment]
My theme
I used a white down triangle with 2 different opacities 
[50% opacity white triangle](https://github.com/bgdz/files/blob/master/pikaday-files/white-down-triangle-opacity-50.png)
[80% opacity white triangle](https://github.com/bgdz/files/blob/master/pikaday-files/white-down-triangle-opacity-80.png)
``` css
 .myTheme .pika-label { background: url(../images/white-down-triangle-opacity-50.png) no-repeat center bottom; }

 .myTheme .pika-label:hover {
background-color: #aaa;
background: url(../images/white-down-triangle-opacity-80.png) no-repeat center 
}
```

**Comment by rikkert** [comment]
Would be nice to have a PR with that theme, please? ;)

**Pull request closed without merging**
