### PR TITLE
Adding themeClass option.

### PR DESCRIPTION
**Pull request by thomasthesecond**
* Accepts a string; returns null otherwise
* Adds the classname to the `pika-single` element
* Classname can then be used in a stylesheet to theme the datepicker (`.pika-single.dark-theme { ... }`)

### CODE REVIEW

**Comment by rikkert** [comment]
Do you have such a theme already?
Than we can add it in the examples.

**Comment by thomasthesecond** [comment]
I can create one for an example.

**Comment by rikkert** [comment]
Yes please and add it to this PR than I can merge.

**Comment by thomasthesecond** [comment]
I've created a theme.html in examples, as well as an example theme.css stylesheet.

**Comment by rikkert** [comment]
Thanks, looks great!

**Pull request merged**
