### PR TITLE
Add options flag for strict date parsing with moment

### PR DESCRIPTION
**Pull request by zerofifteen**
Moment's default parser is very forgiving and translates user typed values into unexpected dates.

If the input format is set to "MM/DD/YYYY", and the user inputs "test5" ... Moment will convert the user input into "05/01/2015".

This flag enables Moment's strict parsing.

### CODE REVIEW

**Comment by jbdietrich** [comment]
Bump. Would also like to see support for strict parsing.

**Comment by benhass** [comment]
@dbushell @rikkert, thanks for your work on this library. I hope you'll consider this PR. Currently, date parsing in multi-locate applications can have unexpected behavior .

**Comment by ilkkao** [comment]
:+1: for adding this useful feature. I'd also like to see no date at all if an invalid date string is typed.

**Comment by nathancahill** [comment]
+1

**Comment by tilmanpotthof** [comment]
+1

**Comment by tilmanpotthof** [comment]
Added an issue for this PR - https://github.com/dbushell/Pikaday/issues/414

**Comment by tilmanpotthof** [comment]
As long as this issue is not release I have a workaround to set the strict parsing as default for moment.

    (function (_, realMoment) {
      'use strict';
    
      // patch moment to parse always strict
      window.moment = function () {
        if (arguments.length === 2) {
          return realMoment.call(realMoment, arguments[0], arguments[1], true);
        } else if (arguments.length === 3 && !_.isBoolean(arguments[2])) {
          return realMoment.call(realMoment, arguments[0], arguments[1], arguments[2], true);
        } else {
          return realMoment.apply(realMoment, arguments);
        }
      };
    
      _.extend(window.moment, realMoment);
    
      if (console && console.warn) {
        console.warn('moment.js strict patch - sets strict:true as hidden default parameter ' +
          '(can be removed if this Pikaday Issue is fixed: https://github.com/dbushell/Pikaday/issues/414');
      }
    })(_, moment);

**Pull request merged**
